name: Check for New Redis Release

on:
  schedule:
    - cron: '30 1 * * *' # Runs daily at 01:30 UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  check-new-release:
    runs-on: ubuntu-latest
    permissions:
      actions: write  # Required to trigger the workflow_dispatch event
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch latest Redis release
        id: fetch-release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/redis/redis/releases/latest | jq -r '.tag_name')
          echo "Latest Redis release: $LATEST_RELEASE"
          echo "latest_release=$LATEST_RELEASE" >> $GITHUB_OUTPUT

      - name: Compare with last known release
        id: compare-release
        run: |
          LAST_KNOWN_RELEASE=$(cat .github/last_known_release.txt || echo "")
          echo "Last known Redis release: $LAST_KNOWN_RELEASE"
          echo "last_known_release=$LAST_KNOWN_RELEASE" >> $GITHUB_OUTPUT
          if [[ "${{ steps.fetch-release.outputs.latest_release }}" != "$LAST_KNOWN_RELEASE" ]]; then
            echo "New release found: ${{ steps.fetch-release.outputs.latest_release }}"
            echo "new_release_found=true" >> $GITHUB_OUTPUT
          else
            echo "No new release found."
            echo "new_release_found=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger build workflow
        if: steps.compare-release.outputs.new_release_found == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'manual-tag.yml',
              ref: context.ref,
              inputs: {
                tag_name: '${{ steps.fetch-release.outputs.latest_release }}',
                make_latest: false,
                prerelease: false
              }
            });
            console.log(`Triggered workflow with release: ${{ steps.fetch-release.outputs.latest_release }}`);

      - name: Notify Telegram - No New Release
        if: steps.compare-release.outputs.new_release_found == 'false'
        uses: appleboy/telegram-action@v1.0.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ℹ️ Daily Redis Release Check
            No new releases found today.
            Last checked version: ${{ steps.compare-release.outputs.last_known_release }}
